[build]
  command = "npm install"
  functions = "functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  included_files = ["data/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/portfolio.html"
  status = 200
